### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by aaravrav142** [roshea6/cpe521-SLAM-project#2]
Hi,
 Can you share the link for the Biocca dataset (bag file). I wish to do some tests on that dataset for feature extraction and I cannot find the dataset on the radish dataset website anymore. Thanks.

**Comment by roshea6** [comment]
Hello,

I believe I originally downloaded the datasets from here: http://www.rawseeds.org/rs/problems/view/10. The bag file was too large for me to store on Github so you'll need to run the extractor script yourself in order to create the bag file.

**Comment by aaravrav142** [comment]
Hi,
Ok thanks for the help. There are two sets of Lidar data in the dataset coming from Hokuyo and Sick Lidar. Which one do you use for the script? 
Thanks.
